baseURL = "https://coffeebytes.dev/"
languageCode = "es-MX"
title = "Coffee bytes"
enableRobotsTXT = true

theme = "hugo-theme-latte"
summaryLength = 40
googleAnalytics = "UA-112824408-2"

[params]
  author = "Eduardo Zepeda"
  description = "Blog personal de Eduardo Zepeda con tutoriales, entradas e información interesante sobre desarrollo web full stack en Python, Django, React, Javascript, Typescript, Golang y otros frameworks de desarrollo, siempre en un entorno de desarrollo basado en GNU/Linux. "


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Categorias"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Sobre mi"
    url = "/pages/eduardo-zepeda-developer"
    weight = 3
  [[menu.main]]
    name = "Reseñas de libros"
    url = "/pages/libros-que-he-leido-y-resenas"
    weight = 3
  [[menu.footer]]
    name = "Politica de privacidad"
    url = "/pages/politica-de-privacidad"
    weight = 4
  [[menu.footer]]
    name = "Politica de cookies"
    url = "/pages/politica-de-cookies"
    weight = 5
  [[menu.social]]
    name = "Twitter"
    pre = "twitter"
    url = "https://twitter.com/hello_wired"
    weight = 6
  [[menu.social]]
    name = "Instagram"
    pre = "instagram"
    url = "https://bit.ly/3jnxnMF"
    weight = 6
  [[menu.social]]
    name = "Linkedin"
    pre = "linkedin-in"
    url = "https://linkedin.com/in/eduardomzepeda"
    weight = 6
  [[menu.social]]
    name = "Codewars"
    pre = "codewars"
    url = "https://www.codewars.com/users/EduardoZepeda"
    weight = 6


[permalinks]
  posts = ":title"

[related]
  includeNewer = false
  threshold = 50
  toLower = true
[[related.indices]]
  name = 'categories'
  weight = 60
[[related.indices]]
  name = 'date'
  weight = 10
