baseURL = "https://coffeebytes.dev/"
languageCode = "es"
title = "Coffee bytes"
enableRobotsTXT = true
DefaultContentLanguage = "es"

theme = "hugo-theme-latte"
summaryLength = 30
googleAnalytics = "UA-112824408-2"
removePathAccents=true

[params]
  excludeFromSitemap = ["tags", "categories", "posts"]
  [params.latte]
    author = "Eduardo Zepeda"
    description = "Artículos y tutoriales sobre desarrollo web y Linux"
    seodescription = "Blog personal de Eduardo Zepeda con tutoriales, entradas e información interesante sobre desarrollo web full stack en Python, Django, React, Javascript, Typescript, Golang y otros frameworks de desarrollo, siempre en un entorno de desarrollo basado en GNU/Linux. "
    toc = true
    disablesearch = false
    mailchimpurl = "https://dev.us17.list-manage.com/subscribe/post?u=5db658017fc3fb83c8ab5ff63&amp;id=c4ad1325c9"
    mailchimphiddenfield = "b_5db658017fc3fb83c8ab5ff63_c4ad1325c9"
    subscribedescription = "✅ Más de 100 desarrolladores registrados. Tutoriales gratuitos cada semana directo en tu correo y cero spam"
    subscribetitle = "Únete"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
    section = ["JSON", "HTML"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Categorias"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Sobre mi"
    url = "/pages/eduardo-zepeda-developer"
    weight = 3
  [[menu.main]]
    name = "Reseñas de libros"
    url = "/pages/libros-que-he-leido-y-resenas"
    weight = 3
  [[menu.footer]]
    name = "Politica de privacidad"
    url = "/pages/politica-de-privacidad"
    weight = 4
  [[menu.footer]]
    name = "Politica de cookies"
    url = "/pages/politica-de-cookies"
    weight = 5
  [[menu.social]]
    name = "Twitter"
    pre = "twitter"
    url = "https://twitter.com/hello_wired"
    weight = 6
  [[menu.social]]
    name = "Instagram"
    pre = "instagram"
    url = "https://bit.ly/3jnxnMF"
    weight = 6
  [[menu.social]]
    name = "Linkedin"
    pre = "linkedin-in"
    url = "https://linkedin.com/in/eduardomzepeda"
    weight = 6
  [[menu.social]]
    name = "Codewars"
    pre = "codewars"
    url = "https://www.codewars.com/users/EduardoZepeda"
    weight = 6


[permalinks]
  posts = ":title"

[related]
  includeNewer = true
  threshold = 70
  toLower = true
  [[related.indices]]
    name = 'categories'
    weight = 50
  [[related.indices]]
    name = 'keywords'
    weight = 50


[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  [markup.goldmark.parser]
    # id tag in table content don't work unluess they're unaccented
    # github-ascii allows only ascii characters which are unaccented
    autoHeadingIDType = 'github-ascii'
