DefaultContentLanguage = "en"
audience = "Software engineers"
author = "Eduardo Zepeda"
baseURL = "https://coffeebytes.dev/"
copyright = "© All rights reserved."
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
googleAnalytics = ""
ignoreLogs = ['warning-goldmark-raw-html']
phAnalytics = ""
removePathAccents = true
theme = "hugo-theme-latte"
title = "Coffee bytes"
[languages]
[languages.en]
disabled = false
languageCode = 'en'
languageDirection = 'ltr'
languageName = 'English'
title = 'Coffee bytes'
weight = 1
[[languages.en.menu.main]]
name = "Hire me"
url = "/en/pages/lets-work-together/"
weight = 2
[[languages.en.menu.main]]
name = "RSS"
url = "/index.xml"
weight = 2
[[languages.en.menu.main]]
name = "About me"
url = "/authors/eduardo-zepeda/"
weight = 3
[[languages.en.menu.footer]]
name = "Privacy policy"
url = "/pages/politica-de-privacidad/"
weight = 5
[[languages.en.menu.footer]]
name = "Cookie policy"
url = "/pages/politica-de-cookies/"
weight = 6
[[languages.en.menu.footer]]
name = "Disclosure"
url = "/pages/disclosure/"
weight = 7
[[languages.en.menu.social]]
name = "Github"
pre = "github-alt"
url = "https://github.com/EduardoZepeda"
weight = 2
[[languages.en.menu.social]]
name = "Threads"
pre = "threads"
url = "https://threads.net/zeedu.dev"
weight = 3
[[languages.en.menu.social]]
name = "Instagram"
pre = "instagram"
url = "https://instagram.com/zeedu.dev"
weight = 4
[[languages.en.menu.social]]
name = "Linkedin"
pre = "linkedin-in"
url = "https://linkedin.com/in/eduardomzepeda"
weight = 5
[[languages.en.menu.social]]
name = "Website"
pre = "message"
url = "https://zeedu.dev"
weight = 6
[languages.en.params]
GoogleTagManager = ""
PostHogAnalytics = "phc_bdNibmcFfhKQR6vm69bRtnnlzgkkO7cOSj44R09E98o"
GoogleAdSenseClient = "ca-pub-testing"
audience = "Software engineers"
author = "Eduardo Zepeda"
description = "My Full-stack Web development blog on Linux with my opinions, tutorials, ideas and rants."
excludeKindFromSitemap = ["section", "term", "taxonomy"]
[languages.en.params.adSlots]
slot0 = "8672022193"
slot1 = "1124666671"
slot2 = "5272667386"
slot3 = "8811585000"
[languages.en.params.latte]
HideAds = false
disablesearch = false
followDescription = "there is a way to get free $200 USD on Digital Ocean (One of the best hosting providers) as a new user? Interested?<div class='prePostAffiliate'><a rel='nofollow' class='affiliate-link affiliate-link-button affiliate-link-button-lg affiliate-shadow' href='https://m.do.co/c/a22240ebb8e7'>Go to Digital Ocean</a></div>"
followRequestDelay = -1
followTitle = "What if I told you that..."
modalcountdown = 250
prePostAffiliateDescription = "You can use it for hosting Javascript, Wordpress, Python, Golang projects, etc."
prePostAffiliateLink = ""
prePostAffiliateText = "Register on Digital Ocean and get FREE $200 USD"
prePostAffiliateTitle = "A gift for my readers: Free USD credits (Valid for 60 days) on DO"
subscribedescription = """
                          ✅ To access just subscribe to the newsletter, it's completely  <strong>completely free.</strong> <br>
                          ✅ Over 400 registered developers. Tutoriales and my ideas on web dev every week, sometimes months, directly in your email, cero spam.
                          """
subscribetitle = "My Python tricks guide for Free"
toc = true

[languages.es]
disabled = false
languageCode = 'es'
languageDirection = 'ltr'
languageName = 'Español'
[[languages.es.menu.main]]
name = "Trabajemos juntos"
url = "/es/pages/trabajemos-juntos/"
weight = 1
[[languages.es.menu.main]]
name = "RSS"
url = "/index.xml"
weight = 2
[[languages.es.menu.main]]
name = "Sobre mi"
url = "/authors/eduardo-zepeda/"
weight = 3
[[languages.es.menu.footer]]
name = "Politica de privacidad"
url = "/pages/politica-de-privacidad/"
weight = 5
[[languages.es.menu.footer]]
name = "Politica de cookies"
url = "/pages/politica-de-cookies/"
weight = 6
[[languages.es.menu.footer]]
name = "Usamos enlaces de afiliados"
url = "/pages/disclosure/"
weight = 7
[[languages.es.menu.social]]
name = "Linkedin"
pre = "linkedin-in"
url = "https://linkedin.com/in/eduardomzepeda"
weight = 2
[[languages.es.menu.social]]
name = "Threads"
pre = "threads"
url = "https://threads.net/zeedu.dev"
weight = 3
[[languages.es.menu.social]]
name = "Instagram"
pre = "instagram"
url = "https://instagram.com/zeedu.dev"
weight = 4
[[languages.es.menu.social]]
name = "Website"
pre = "message"
url = "https://zeedu.dev"
weight = 5
[[languages.es.menu.social]]
name = "Github"
pre = "github-alt"
url = "https://github.com/EduardoZepeda"
weight = 6
[languages.es.params]
GoogleTagManager = ""
PostHogAnalytics = "phc_bdNibmcFfhKQR6vm69bRtnnlzgkkO7cOSj44R09E98o"
GoogleAdSenseClient = "ca-pub-testing"
audience = "Software engineers"
author = "Eduardo Zepeda"
description = "Mi Blog de Desarrollo Web Full-stack en Linux con mis opiniones, tutoriales, ideas and críticas."
excludeKindFromSitemap = ["section", "term", "taxonomy"]
[languages.es.params.adSlots]
slot0 = "8672022193"
slot1 = "1124666671"
slot2 = "5272667386"
slot3 = "8811585000"
[languages.es.params.latte]
HideAds = false
disablesearch = false
followDescription = "existe una manera de obtener $200 USD totalmente gratis en Digital Ocean (uno de los mejores proveedores de hosting). ¿Te interesa saber como? <div class='prePostAffiliate'><a rel='nofollow' class='affiliate-link affiliate-link-button affiliate-link-button-lg affiliate-shadow' href='https://m.do.co/c/a22240ebb8e7'>Entrar a Digital Ocean</a></div>"
followRequestDelay = -1
followTitle = "¿Y si te digo que..."
mailchimphiddenfield = "b_5db658017fc3fb83c8ab5ff63_c4ad1325c9"
mailchimpurl = "https://dev.us17.list-manage.com/subscribe/post?u=5db658017fc3fb83c8ab5ff63&amp;id=c4ad1325c9"
modalcountdown = 120
prePostAffiliateDescription = "Utiliza este crédito para lanzar tus proyectos ahora en Digital Ocean, válido por 60 días"
prePostAffiliateLink = ""
prePostAffiliateText = "Quiero registrarme y obtener $200 USD"
prePostAffiliateTitle = "No te pierdas este crédito gratuito de 200 USD (Válido durante 60 días) en DO, lanza tu proyecto ahora"
subscribedescription = """No, no te harás millonario, tampoco un rockstar de la programación, probablemente solo aprendas sobre los temas que considero interesantes. <br>
                          - Más de 400 devs suscritos <br>
                          - Incluye <strong>Gratis mi Guía de Python</strong> <br>
                          - Es completamente gratis <br>
                          """
subscribetitle = "Recibe más posts como este, solo eso"
toc = true

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.9

[outputs]

home = ["HTML", "RSS"]
page = ["HTML", "JSON", "RSS"]
section = ["HTML", "RSS", "JSON"]

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[permalinks]
categories = "/:slug"
pages = "/pages/:contentbasename/"
posts = "/:sections[1:]/:title"
sections = "/:sections[1:]/:slug"

[languages.es.permalinks]
categories = "/:slug"
posts = "/:slug"

[related]
includeNewer = true
threshold = 70
toLower = true
[[related.indices]]
name = 'categories'
weight = 50
[[related.indices]]
name = 'keywords'
weight = 50

[markup]
[markup.highlight]
style = "base16-snazzy"
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2
[markup.goldmark.parser]
# id tag in table content don't work unluess they're unaccented
# github-ascii allows only ascii characters which are unaccented
autoHeadingIDType = 'github-ascii'
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
[params.csp]
child-src = ["'self'"]
font-src = ["*"]
form-action = ["'self'", "https://dev.us17.list-manage.com"]
frame-src = [
  "'self'",
  "*.twitter.com",
  "*.x.com",
  "*.youtube.com",
  " *.googletagmanager.com",
  "*.doubleclick.net",
  "*.google.com",
  "https://ep2.adtrafficquality.google",
  "https://ep2.adtrafficquality.google/*",
  "https://ep2.adtrafficquality.google/sodar/sodar2/232/runner.html",
]
img-src = [
  "*",
]

frame-ancestors = ["'self'"]
object-src = ["'self'"]
script-src = [
  "'self'",
  "'unsafe-inline'",
  "*.cloudflare.com",
  "*.doubleclick.net",
  "https://platform.twitter.com",
  "https://cdn.syndication.twimg.com",
  "*.amazon.com",
  "*.amazon-adsystem.com",
  "https://www.google-analytics.com",
  "*.google",
  "https://www.google.com",
  "https://pagead2.googlesyndication.com",
  "https://adservice.google.com",
  "https://ep2.adtrafficquality.google",
  "https://www.googletagservices.com",
  "https://googleads.g.doubleclick.net",
  "jsfiddle.net",
  "*.instagram.com",
  "*.twitter.com",
  "*.x.com",
  "*.googletagmanager.com",
  "https://unpkg.com/@iconify-json/logos@1/icons.json",
  "data: pagead2.googlesyndication.com storage.googleapis.com googleads.g.doubleclick.net ajax.googleapis.com",
  "https://unpkg.com/htmx.org@2.0.4",
  "https://unpkg.com/htmx-ext-head-support@2.0.2",
  "https://unpkg.com/lunr/lunr.js",
  "https://us-assets.i.posthog.com",
  "https://unpkg.com/react@18/umd/react.development.js",
  "https://unpkg.com/react-dom@18/umd/react-dom.development.js",
  "https://unpkg.com/@babel/standalone/babel.min.js",
  "https://d3js.org/d3.v7.min.js",
  "https://res.cloudinary.com/dwrscezd2/raw/upload/",
]
style-src = [
  "'self'",
  "'unsafe-inline'",
  "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css",
]
[caches]
[caches.images]
dir = ':resourceDir/_gen'
maxAge = "72h"
[caches.getresource]
dir = ':resourceDir/_gen'
maxAge = "24h"

[security.http]
mediaTypes = ['application/vnd\.api\+json', 'image/avif', 'image/jpeg', 'image/png', 'image/jpg']

[pagination]
pagerSize = 9
