DefaultContentLanguage = "en"
audience = "Web developers"
author = "Eduardo Zepeda"
baseURL = "https://coffeebytes.dev/"
copyright = "© All rights reserved."
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
googleAnalytics = "G-P84BC2GXX4"
removePathAccents = true
theme = "hugo-theme-latte"
title = "Coffee bytes"

[languages]
[languages.en]
disabled = false
languageCode = 'en'
languageDirection = 'ltr'
languageName = 'English'
title = 'Coffee bytes'
weight = 1
[[languages.en.menu.main]]
name = "Hire me"
url = "/en/pages/lets-work-together/"
weight = 2
[[languages.en.menu.main]]
name = "RSS"
url = "/index.xml"
weight = 2
[[languages.en.menu.main]]
name = "About me"
url = "/authors/eduardo-zepeda/"
weight = 3
[[languages.en.menu.main]]
name = "Go tutorial"
url = "/en/pages/go-programming-language-tutorial/"
weight = 4
[[languages.en.menu.footer]]
name = "Privacy policy"
url = "/pages/politica-de-privacidad/"
weight = 5
[[languages.en.menu.footer]]
name = "Cookie policy"
url = "/pages/politica-de-cookies/"
weight = 6
[[languages.en.menu.footer]]
name = "Disclosure"
url = "/pages/disclosure/"
weight = 7
[[languages.en.menu.social]]
name = "Codewars"
pre = "codewars"
url = "https://www.codewars.com/users/EduardoZepeda"
weight = 2
[[languages.en.menu.social]]
name = "Threads"
pre = "threads"
url = "https://threads.net/zeedu.dev"
weight = 3
[[languages.en.menu.social]]
name = "Instagram"
pre = "instagram"
url = "https://instagram.com/zeedu.dev"
weight = 4
[[languages.en.menu.social]]
name = "Linkedin"
pre = "linkedin-in"
url = "https://linkedin.com/in/eduardomzepeda"
weight = 5
[[languages.en.menu.social]]
name = "Website"
pre = "message"
url = "https://zeedu.dev"
weight = 6
[languages.en.params]
GoogleTagManager = "GTM-5F4NMW3"
audience = "Web developers"
author = "Eduardo Zepeda"
description = "Tutorials and acid opinions about web development, programming and technology"
excludeKindFromSitemap = ["section", "term", "taxonomy"]
[languages.en.params.latte]
disablesearch = false
modalcountdown = 2
prePostAffiliateDescription = "You have no excuses now, use this free credit to launch your projects now on Digital Ocean, you're free to spend it whenever you want within the following 60 days."
prePostAffiliateLink = "https://m.do.co/c/a22240ebb8e7"
prePostAffiliateText = "Get FREE $200 USD credit now"
prePostAffiliateTitle = "Don't miss this free $200 USD credit (Valid for 60 days) on DO, launch your idea now"
subscribebannertext = "Get my FREE Python cheats guide."
subscribedescription = """
                          ✅ To access just subscribe to the newsletter, it's completely  <strong>completely free.</strong> <br>
                          ✅ Over 400 registered developers. Tutoriales and my ideas on web dev every week, sometimes months, directly in your email, cero spam.
                          """
subscribetitle = "My Python tricks guide for Free"
toc = true

[languages.es]
disabled = false
languageCode = 'es'
languageDirection = 'ltr'
languageName = 'Español'
[[languages.es.menu.main]]
name = "Contrátame"
url = "/es/pages/trabajemos-juntos/"
weight = 1
[[languages.es.menu.main]]
name = "RSS"
url = "/index.xml"
weight = 2
[[languages.es.menu.main]]
name = "Sobre mi"
url = "/authors/eduardo-zepeda/"
weight = 3
[[languages.es.menu.main]]
name = "Tutorial de Go"
url = "/es/pages/go-programming-language-tutorial/"
weight = 4
[[languages.es.menu.footer]]
name = "Politica de privacidad"
url = "/pages/politica-de-privacidad/"
weight = 5
[[languages.es.menu.footer]]
name = "Politica de cookies"
url = "/pages/politica-de-cookies/"
weight = 6
[[languages.es.menu.footer]]
name = "Usamos enlaces de afiliados"
url = "/pages/disclosure/"
weight = 7
[[languages.es.menu.social]]
name = "Codewars"
pre = "codewars"
url = "https://www.codewars.com/users/EduardoZepeda"
weight = 2
[[languages.es.menu.social]]
name = "Threads"
pre = "threads"
url = "https://threads.net/zeedu.dev"
weight = 3
[[languages.es.menu.social]]
name = "Instagram"
pre = "instagram"
url = "https://instagram.com/zeedu.dev"
weight = 4
[[languages.es.menu.social]]
name = "Linkedin"
pre = "linkedin-in"
url = "https://linkedin.com/in/eduardomzepeda"
weight = 5
[[languages.es.menu.social]]
name = "Website"
pre = "message"
url = "https://zeedu.dev"
weight = 6
[languages.es.params]
GoogleTagManager = "GTM-5F4NMW3"
audience = "Web developers"
author = "Eduardo Zepeda"
description = "Artículos, opiniones ácidas y tutoriales sobre programación web, desarrollo y tecnología"
excludeKindFromSitemap = ["section", "term", "taxonomy"]
[languages.es.params.latte]
disablesearch = false
mailchimphiddenfield = "b_5db658017fc3fb83c8ab5ff63_c4ad1325c9"
mailchimpurl = "https://dev.us17.list-manage.com/subscribe/post?u=5db658017fc3fb83c8ab5ff63&amp;id=c4ad1325c9"
modalcountdown = 2
prePostAffiliateDescription = "Utiliza este crédito gratuito para lanzar tus proyectos ahora en Digital Ocean, eres libre de gastarlo cuando quieras en los siguientes 60 días."
prePostAffiliateLink = "https://m.do.co/c/a22240ebb8e7"
prePostAffiliateText = "Obtén $200 USD Gratis ya"
prePostAffiliateTitle = "No te pierdas este crédito gratuito de 200 USD (Válido durante 60 días) en DO, lanza tu proyecto ahora"
subscribebannertext = "¡Llévate GRATIS mi guía de trucos de Python!"
subscribedescription = """
                          ✅ Para acceder solo suscríbete al newsletter, es <strong>completamente gratis.</strong> <br>
                          ✅ Tutoriales, opiniones y cosas que encuentro interesantes completamente gratuitos solo un par de veces por mes :) directo en tu correo y cero spam.
                          """
subscribetitle = "¡GRATIS! Guía de trucos de Python."
toc = true

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.9

[outputs]

home = ["HTML", "RSS"]
page = ["HTML", "JSON", "RSS"]
section = ["HTML", "RSS", "JSON"]

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[permalinks]
pages = "/pages/:filename/"
posts = ":title"

[related]
includeNewer = true
threshold = 70
toLower = true
[[related.indices]]
name = 'categories'
weight = 50
[[related.indices]]
name = 'keywords'
weight = 50

[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2
[markup.goldmark.parser]
# id tag in table content don't work unluess they're unaccented
# github-ascii allows only ascii characters which are unaccented
autoHeadingIDType = 'github-ascii'

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[params.csp]
child-src = ["'self'"]
font-src = ["'self'"]
form-action = ["'self'"]
frame-src = ["'self'", "*.twitter.com", "*.x.com", "*.youtube.com"]
img-src = [
  "https://i.imgflip.com",
  "'self'",
  "*.cloudinary.com",
  "*.amazonaws.com",
  "*.codewars.com",
  "*.google.com",
  "*.google.com.mx",
  "*.googletagmanager.com",
  "https://htmx.org",
]
object-src = ["'none'"]
script-src = [
  "'self'",
  "'unsafe-inline'",
  "*.cloudflare.com",
  "*.doubleclick.net",
  "https://platform.twitter.com",
  "https://cdn.syndication.twimg.com",
  "*.amazon-adsystem.com",
  "https://www.google-analytics.com",
  "cse.google.com",
  "https://www.google.com",
  "https://pagead2.googlesyndication.com",
  "https://adservice.google.com",
  "https://www.googletagservices.com",
  "jsfiddle.net",
  "*.instagram.com",
  "*.twitter.com",
  "*.x.com",
  "*.googletagmanager.com",
]
style-src = ["'self'", "'unsafe-inline'"]

[caches]
[caches.images]
dir = ':resourceDir/_gen'
maxAge = "72h"
[caches.getresource]
dir = ':resourceDir/_gen'
maxAge = "24h"

[security.http]
mediaTypes = ['application/vnd\.api\+json', 'image/avif', 'image/jpeg', 'image/png', 'image/jpg']
