DefaultContentLanguage = "es"
author = "Eduardo Zepeda"
baseURL = "https://coffeebytes.dev/"
enableRobotsTXT = true
languageCode = 'es-MX'
title = "Coffee bytes"

googleAnalytics = "G-P84BC2GXX4"
removePathAccents = true
summaryLength = 30
theme = "hugo-theme-latte"

[languages]
[languages.en]
disabled = true
languageCode = 'en'
languageDirection = ''
languageName = ''
title = ''
weight = 0
[languages.es]
disabled = false
languageDirection = 'ltr'
languageName = 'Español'

[params]
GoogleTagManager = "GTM-5F4NMW3"
description = "Artículos y tutoriales sobre programación y desarrollo web: Django, React, Go en Linux"
excludeFromSitemap = ["tags", "categories", "posts", "pages"]
[params.latte]
disablesearch = false
mailchimphiddenfield = "b_5db658017fc3fb83c8ab5ff63_c4ad1325c9"
mailchimpurl = "https://dev.us17.list-manage.com/subscribe/post?u=5db658017fc3fb83c8ab5ff63&amp;id=c4ad1325c9"
modalcountdown = 20
seodescription = "Blog personal de Eduardo Zepeda con tutoriales, entradas e información interesante sobre desarrollo web full stack en Python, Django, React, Javascript, Typescript, Golang y otros frameworks de desarrollo, siempre en un entorno de desarrollo basado en GNU/Linux. "
subscribebannertext = "¡Llévate completamente GRATIS mi guía de trucos de Python."
subscribedescription = """
                          ✅ Para acceder solo suscríbete al newsletter, es <strong>completamente gratis.</strong> <br>
                          ✅ Más de 400 desarrolladores registrados. Tutoriales y reflexiones completamente gratuitos cada semana, a veces meses :) directo en tu correo y cero spam.
                          """
subscribetitle = "¡GRATIS! Guía de trucos de Python."
toc = true

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]
section = ["HTML", "RSS", "JSON"]

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 2
[[menu.main]]
name = "Categorías"
url = "/categories/"
weight = 3
[[menu.main]]
name = "Sobre mi"
url = "/authors/eduardo-zepeda/"
weight = 4
[[menu.main]]
name = "Reseñas de libros"
url = "/pages/libros-que-he-leido-y-resenas/"
weight = 5
[[menu.footer]]
name = "Politica de privacidad"
url = "/pages/politica-de-privacidad/"
weight = 4
[[menu.footer]]
name = "Politica de cookies"
url = "/pages/politica-de-cookies/"
weight = 5
[[menu.social]]
name = "Personal website"
pre = "message"
url = "https://eduardozepeda.dev/"
weight = 1
[[menu.social]]
name = "Codewars"
pre = "codewars"
url = "https://www.codewars.com/users/EduardoZepeda"
weight = 2
[[menu.social]]
name = "Twitter"
pre = "twitter"
url = "https://twitter.com/hello_wired"
weight = 3
[[menu.social]]
name = "Instagram"
pre = "instagram"
url = "https://instagram.com/eduardozepeda.dev"
weight = 4
[[menu.social]]
name = "Linkedin"
pre = "linkedin-in"
url = "https://linkedin.com/in/eduardomzepeda"
weight = 5

[permalinks]
pages = "/pages/:filename/"
posts = ":title"

[related]
includeNewer = true
threshold = 70
toLower = true
[[related.indices]]
name = 'categories'
weight = 50
[[related.indices]]
name = 'keywords'
weight = 50

[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2
[markup.goldmark.parser]
# id tag in table content don't work unluess they're unaccented
# github-ascii allows only ascii characters which are unaccented
autoHeadingIDType = 'github-ascii'

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
