baseURL = "https://coffeebytes.dev/"
title = "Coffee bytes"
enableRobotsTXT = true
DefaultContentLanguage = "es"
languageCode = 'es-MX'
author = "Eduardo Zepeda"

theme = "hugo-theme-latte"
summaryLength = 30
googleAnalytics = "UA-112824408-2"
removePathAccents=true

[language]
lang = "es"

[Author]
  name = 'Eduardo Zepeda'
  email = 'eduardozepeda@coffeebytes.dev'

[params]
  excludeFromSitemap = ["tags", "categories", "posts"]
  description = "Artículos sobre desarrollo web y Linux."
  author = "Eduardo Zepeda"
  authorDescription = "Desarrollador web y entusiasta de GNU/Linux. Me siento bastante cómodo usando Python, Javascript/Typescript y Go: el odiado lenguaje de la mascotita azul. También creo en las bondades de la criptografía fuera de la especulación monetaria. Mensaje secreto en Vigenere: Yy pgkvnvm yw tvdmg k bp oqntq yonaqniomm dxzdeu. Mgz emzr, rdcyvqkanyyymm znumszl kdepfcqbkjs a ocpgkda huwnbwi. Lkzepwqi mg bucxkz swbyc izztgzwthaj y hmfdh, xjr na kfx, ad pwpcdmm gegd ydmw vgtqalfm zn Vicemmm."
  authorImg = "https://res.cloudinary.com/eduardozepeda/image/upload/v1665799941/media/user_1/yo_bocvvt.jpg"
  
  [params.latte]
    seodescription = "Blog personal de Eduardo Zepeda con tutoriales, entradas e información interesante sobre desarrollo web full stack en Python, Django, React, Javascript, Typescript, Golang y otros frameworks de desarrollo, siempre en un entorno de desarrollo basado en GNU/Linux. "
    toc = true
    disablesearch = false
    mailchimpurl = "https://dev.us17.list-manage.com/subscribe/post?u=5db658017fc3fb83c8ab5ff63&amp;id=c4ad1325c9"
    mailchimphiddenfield = "b_5db658017fc3fb83c8ab5ff63_c4ad1325c9"
    subscribedescription = """
                          ✅ Para acceder solo suscríbete al newsletter, es <strong>completamente gratis.</strong> <br>
                          ✅ Más de 200 desarrolladores registrados. Tutoriales completamente gratuitos cada semana directo en tu correo y cero spam.
                          """
    subscribetitle = "¡GRATIS! Guía de trucos de Python."
    modalcountdown = 20
    subscribebannertext = "¡Llévate GRATIS mi guía de trucos de Python."

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
    home = ["HTML", "RSS"]
    section = ["HTML", "RSS", "JSON"]
    page = ["HTML", "RSS"]

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 2
  [[menu.main]]
    name = "Categorías"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "Sobre mi"
    url = "/pages/eduardo-zepeda-developer"
    weight = 4
  [[menu.main]]
    name = "Reseñas de libros"
    url = "/pages/libros-que-he-leido-y-resenas"
    weight = 5
  [[menu.footer]]
    name = "Politica de privacidad"
    url = "/pages/politica-de-privacidad"
    weight = 4
  [[menu.footer]]
    name = "Politica de cookies"
    url = "/pages/politica-de-cookies"
    weight = 5
  [[menu.social]]
    name = "Personal website"
    pre = "message"
    url = "https://eduardozepeda.dev/"
    weight = 1
  [[menu.social]]
    name = "Codewars"
    pre = "codewars"
    url = "https://www.codewars.com/users/EduardoZepeda"
    weight = 2
  [[menu.social]]
    name = "Twitter"
    pre = "twitter"
    url = "https://twitter.com/hello_wired"
    weight = 3
  [[menu.social]]
    name = "Instagram"
    pre = "instagram"
    url = "https://bit.ly/3jnxnMF"
    weight = 4
  [[menu.social]]
    name = "Linkedin"
    pre = "linkedin-in"
    url = "https://linkedin.com/in/eduardomzepeda"
    weight = 5

[permalinks]
  posts = ":title"

[related]
  includeNewer = true
  threshold = 70
  toLower = true
  [[related.indices]]
    name = 'categories'
    weight = 50
  [[related.indices]]
    name = 'keywords'
    weight = 50


[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  [markup.goldmark.parser]
    # id tag in table content don't work unluess they're unaccented
    # github-ascii allows only ascii characters which are unaccented
    autoHeadingIDType = 'github-ascii'