DefaultContentLanguage = "es"
author = "Eduardo Zepeda"
baseURL = "https://coffeebytes.dev/"
enableRobotsTXT = true
title = "Coffee bytes"

googleAnalytics = "G-P84BC2GXX4"
removePathAccents = true
summaryLength = 30
theme = "hugo-theme-latte"

defaultContentLanguageInSubdir = true

[languages]
[languages.en]
disabled = false
languageCode = 'en'
languageDirection = 'ltr'
languageName = 'English'
title = 'Coffee bytes'
weight = 1
[[languages.en.menu.main]]
name = "RSS"
url = "/index.xml"
weight = 2
[[languages.en.menu.main]]
name = "Categories"
url = "/categories/"
weight = 3
[[languages.en.menu.main]]
name = "About me"
url = "/authors/eduardo-zepeda/"
weight = 4
[[languages.en.menu.main]]
name = "Book reviews"
url = "/pages/libros-que-he-leido-y-resenas/"
weight = 5
[[languages.en.menu.footer]]
name = "Privacy policy"
url = "/pages/politica-de-privacidad/"
weight = 4
[[languages.en.menu.footer]]
name = "Cookie policy"
url = "/pages/politica-de-cookies/"
weight = 5
[[languages.en.menu.social]]
name = "Personal website"
pre = "message"
url = "https://eduardozepeda.dev/"
weight = 1
[[languages.en.menu.social]]
name = "Codewars"
pre = "codewars"
url = "https://www.codewars.com/users/EduardoZepeda"
weight = 2
[[languages.en.menu.social]]
name = "Twitter"
pre = "twitter"
url = "https://twitter.com/hello_wired"
weight = 3
[[languages.en.menu.social]]
name = "Instagram"
pre = "instagram"
url = "https://instagram.com/eduardozepeda.dev"
weight = 4
[[languages.en.menu.social]]
name = "Linkedin"
pre = "linkedin-in"
url = "https://linkedin.com/in/eduardomzepeda"
weight = 5
[languages.en.params]
GoogleTagManager = "GTM-5F4NMW3"
description = "Opinions and tutorials about web development and programming"
excludeKindFromSitemap = ["section", "term", "taxonomy"]
[languages.en.params.latte]
disablesearch = false
mailchimphiddenfield = ""
mailchimpurl = ""
modalcountdown = 20
subscribebannertext = "Get my FREE Python cheats guide."
subscribedescription = """
                          ✅ To access just subscribe to the newsletter, it's completely  <strong>completely free.</strong> <br>
                          ✅ Over 400 registered developers. Tutoriales and my ideas on web dev every week, sometimes months, directly in your email, cero spam.
                          """
subscribetitle = "Free my Python tricks guide"
toc = true

[languages.es]
disabled = false
languageCode = 'es'
languageDirection = 'ltr'
languageName = 'Español'
[[languages.es.menu.main]]
name = "RSS"
url = "/index.xml"
weight = 2
[[languages.es.menu.main]]
name = "Categorías"
url = "/categories/"
weight = 3
[[languages.es.menu.main]]
name = "Sobre mi"
url = "/authors/eduardo-zepeda/"
weight = 4
[[languages.es.menu.main]]
name = "Reseñas de libros"
url = "/pages/libros-que-he-leido-y-resenas/"
weight = 5
[[languages.es.menu.footer]]
name = "Politica de privacidad"
url = "/pages/politica-de-privacidad/"
weight = 4
[[languages.es.menu.footer]]
name = "Politica de cookies"
url = "/pages/politica-de-cookies/"
weight = 5
[[languages.es.menu.social]]
name = "Personal website"
pre = "message"
url = "https://eduardozepeda.dev/"
weight = 1
[[languages.es.menu.social]]
name = "Codewars"
pre = "codewars"
url = "https://www.codewars.com/users/EduardoZepeda"
weight = 2
[[languages.es.menu.social]]
name = "Twitter"
pre = "twitter"
url = "https://twitter.com/hello_wired"
weight = 3
[[languages.es.menu.social]]
name = "Instagram"
pre = "instagram"
url = "https://instagram.com/eduardozepeda.dev"
weight = 4
[[languages.es.menu.social]]
name = "Linkedin"
pre = "linkedin-in"
url = "https://linkedin.com/in/eduardomzepeda"
weight = 5
[languages.es.params]
GoogleTagManager = "GTM-5F4NMW3"
description = "Artículos, opiniones y tutoriales sobre desarrollo web y programación"
excludeKindFromSitemap = ["section", "term", "taxonomy"]
[languages.es.params.latte]
disablesearch = false
mailchimphiddenfield = "b_5db658017fc3fb83c8ab5ff63_c4ad1325c9"
mailchimpurl = "https://dev.us17.list-manage.com/subscribe/post?u=5db658017fc3fb83c8ab5ff63&amp;id=c4ad1325c9"
modalcountdown = 20
subscribebannertext = "¡Llévate completamente GRATIS mi guía de trucos de Python."
subscribedescription = """
                          ✅ Para acceder solo suscríbete al newsletter, es <strong>completamente gratis.</strong> <br>
                          ✅ Más de 400 desarrolladores registrados. Tutoriales y reflexiones completamente gratuitos cada semana, a veces meses :) directo en tu correo y cero spam.
                          """
subscribetitle = "¡GRATIS! Guía de trucos de Python."
toc = true

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]
section = ["HTML", "RSS", "JSON"]

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[permalinks]
pages = "/pages/:filename/"
posts = ":title"

[related]
includeNewer = true
threshold = 70
toLower = true
[[related.indices]]
name = 'categories'
weight = 50
[[related.indices]]
name = 'keywords'
weight = 50

[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2
[markup.goldmark.parser]
# id tag in table content don't work unluess they're unaccented
# github-ascii allows only ascii characters which are unaccented
autoHeadingIDType = 'github-ascii'

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[params.csp]
child-src = ["'self'"]
font-src = ["'self'"]
form-action = ["'self'"]
frame-src = ["'self'", "*.twitter.com", "*.x.com", "*.youtube.com"]
img-src = ["'self'", "*.cloudinary.com", "*.codewars.com", "*.google.com", "*.google.com.mx"]
object-src = ["'none'"]
script-src = [
  "'self'",
  "'unsafe-inline'",
  "*.cloudflare.com",
  "*.doubleclick.net",
  "https://platform.twitter.com",
  "https://cdn.syndication.twimg.com",
  "*.amazon-adsystem.com",
  "https://www.google-analytics.com",
  "cse.google.com",
  "https://www.google.com",
  "https://pagead2.googlesyndication.com",
  "https://adservice.google.com",
  "https://www.googletagservices.com",
  "jsfiddle.net",
  "*.instagram.com",
  "*.twitter.com",
  "*.x.com",
  "*.googletagmanager.com",
]
style-src = ["'self'", "'unsafe-inline'"]
