baseURL = "https://coffeebytes.dev/"
languageCode = "es-MX"
title = "Coffee bytes"

theme = "hugo-theme-latte"
summaryLength = 40

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.footer]]
    name = "Politica de privacidad"
    url = "/politica-de-privacidad/"
    weight = 4
  [[menu.footer]]
    name = "Politica de cookies"
    url = "/politica-de-cookies/"
    weight = 5
  [[menu.social]]
    name = "Twitter"
    pre = "twitter"
    url = "/politica-de-privacidad/"
    weight = 6
  [[menu.social]]
    name = "Instagram"
    pre = "instagram"
    url = "/politica-de-privacidad/"
    weight = 6
  [[menu.social]]
    name = "Linkedin"
    pre = "linkedin-in"
    url = "/politica-de-privacidad/"
    weight = 6


[permalinks]
  posts = ":title"

